CREATE TABLE TOPICOS(
	ID INT auto_increment,
    TITULO VARCHAR(255) NOT NULL,
    MENSAGEM VARCHAR(500) NOT NULL,
    DATA_CRIACAO DATETIME,
    STATUS VARCHAR(30),
    ID_AUTOR INT ,
    ID_CURSO INT(50) , primary key (ID)
);